### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by theastar**
See \Sensio\Bundle\FrameworkExtraBundle\DependencyInjection\SensioFrameworkExtraExtension

### CODE REVIEW

**Comment by jvasseur** [comment]
The security config key (and the associated listeners) don't exists on the 2.3 branch.

**Comment by theastar** [comment]
Sorry. Is it possible for the following page to have a version for Symfony 2.7? http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/index.html

Anyways, just my two cents

**Comment by jvasseur** [comment]
The page you linked is the one to use.

This bundle version is not synced with the Symfony version (http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/index.html#release-cycle-note) so you should be using the 3.0 doc.

**Comment by theastar** [comment]
Yup - noted, thanks. Will do

**Pull request closed without merging**
