### PR TITLE
Fixes support for doctrine/persistence 2.x

### PR DESCRIPTION
**Pull request by fruitwasp**

### CODE REVIEW

**Comment by andrea-daru** [comment]
I need this fix to be released because it's blocking for my project.
@fruitwasp do you know when it will be released?

**Comment by michaljusiega** [comment]
cc @fabpot - Can you tell when this fix will be released ?

**Comment by fabpot** [comment]
Apparently, the tests are broken, so it cannot be merged as is.

**Comment by jhfyang** [comment]
Hello is it possible to try to import with :
`use Symfony\Bridge\Doctrine\ManagerRegistry;` ?

**Comment by fabpot** [comment]
Taking over as Doctrine, once again, broke BC the hard way.

**Comment by fabpot** [comment]
Thank you @fruitwasp.

**Comment by fabpot** [comment]
This is due to a BC break in Doctrine (see https://github.com/doctrine/DoctrineBundle/pull/1202). Fixed now in v5.6.0. Everything should work again.

**Pull request merged**
