### PR TITLE
Fix Symfony 6 BC break with required attributes in routing.xml

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/758

Closes https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/721

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @TomasVotruba.

**Comment by sprain** [comment]
With this change I now get the following error in a Symfony 4.4 project:

```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                                                                                                                                                                                                                          
Unable to parse file "/var/www/html/vendor/sensio/framework-extra-bundle/src/DependencyInjection/../Resources/config/routing.xml":
[ERROR 1827] Element '{http://symfony.com/schema/dic/services}deprecated', attribute 'package': The attribute 'package' is not allowed.
 ```
  
 I am trying to find the root cause, but maybe it's obvious to you and you can give me a hint?

**Comment by TomasVotruba** [comment]
This bundle should be probably limited in composer.json to Symfony 5.4 and 6 only. Otherwise there will be always one major Symfony version unhappy about the config :)

**Comment by derrabus** [comment]
> This bundle should be probably limited in composer.json to Symfony 5.4 and 6 only.

Maybe, but right now it isn't. We should make the bundle compatible with 4.4 again.

**Comment by fabpot** [comment]
Reverted and new version released.

**Comment by fabpot** [comment]
Is anyone willing to work on another fix that makes the code work for all versions? As the `routing.xml` file is deprecated anyway, what about having 2 XML files: one compatible with 4.4 and another one for 5+? And we load the right one in SensioFrameworkExtraExtension.

**Comment by phiphou** [comment]
> Reverted and new version released.

I don't understand why you revert these changes, they were for me the only way to get rid of the error message...

**Pull request merged**
