### PR TITLE
Version 4 of the bundle

### PR DESCRIPTION
**Pull request by fabpot**
From the CHANGELOG:

* removed support for the Templating component (only plain Twig is supported)
* removed unneeded phpdocs, converted protected to private properties
* bumped Symfony minimum version to 3.0
* bumped PHP minimum version to 5.5.9
* removed class parameters in container definitions

### CODE REVIEW

**Comment by Koc** [comment]
@fabpot oh, no! Can you merge #430 into 3.x first, please?

**Comment by iltar** [comment]
LGTM, BC wise there's nothing I foresee any issues with but I can't say I've extended the annotations. As soon as this is merged, I will hook it up in one of our applications to see if anything breaks (doubt it).

**Comment by iltar** [comment]
If the minimum requirement for the http-kernel can be bumped to 3.1, the `PsrServerRequestParamConverter` could be turned into an `ArgumentValueResolver`: https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/Request/ParamConverter/PsrServerRequestParamConverter.php

**Comment by fabpot** [comment]
3.0 is not supported anymore anyway, so totally possible. Can you work on a patch?

**Comment by iltar** [comment]
I'll see if I have an hour to spare tomorrow

**Comment by weaverryan** [comment]
👍 I just tested this with The Symfony Demo, which uses many of these features and had no issue (tests pass too).

**Comment by iltar** [comment]
@fabpot see #433

**Pull request merged**
