### PR TITLE
Fix tests and add PHP 7.2

### PR DESCRIPTION
**Pull request by alcaeus**

### CODE REVIEW

**Comment by alcaeus** [comment]
Note: can't reproduce the deprecations on my machine - anyone have suggestions how to fix?

**Comment by fabpot** [comment]
I've fixed the CS in be47a02

**Comment by alcaeus** [comment]
Thanks @fabpot, I've rebased on top but still need to address the deprecation warnings to get the builds stable.

**Comment by fabpot** [comment]
merging this one as this is still an improvement over the current situation.

**Comment by fabpot** [comment]
Thank you @alcaeus.

**Pull request merged**
