### PR TITLE
Remove PSR-7 support

### PR DESCRIPTION
**Pull request by fabpot**
People have issues with it (#620, #709, ...) and it does not have to be part of this bundle (I've never used it myself and would never recommend anyone to use it anyway, it adds overhead for no benefits).

If someone wants it, creating a new bundle is the way to go.

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by Tobion** [comment]
Aren't you adding deprecations for this first?

**Comment by fabpot** [comment]
I'll let someone do the PR if that's something useful.

**Comment by ajgarlag** [comment]
I have released [`ajgarlag/psr-http-message-bundle`](https://github.com/ajgarlag/psr-http-message-bundle). It adds PSR-7 support to Symfony Framework apps.

I hope it can help anyone depending on this removed feature. Any feedback is welcome.

**Comment by Tobion** [comment]
See https://github.com/symfony/psr-http-message-bridge/pull/89 and https://github.com/symfony/recipes/pull/899 for the new solution of this feature.

**Pull request merged**
