### PR TITLE
Adds not_found_message configuration to Doctrine ParamConverter

### PR DESCRIPTION
**Pull request by makarova**
Adds possibility to customize not found exception message in doctrine param converter by using not_found_message configuration property

### CODE REVIEW

**Comment by apfelbox** [comment]
See #196

**Comment by makarova** [comment]
@apfelbox I saw that issue but still think that it is very convenient to have possibility to customize error message, especially if it is so simple to implement

**Comment by ghanbari** [comment]
I use multiply `@ParamConvertor` on my method and i want show a appropriate message, but i can not detect in `404.json.twig`, which object wasn't found,

also i use **fos rest bundle** that permit to me show exception message to user, but i no want show class name to final user, (that is a good ability, if and if i can customize exception message)

**Comment by ghanbari** [comment]
I use multiply `@ParamConvertor` on my method and i want show a appropriate message, but i can not detect in `404.json.twig`, which object wasn't found,

also i use **fos rest bundle** that permit to me show exception message to user, but i no want show class name to final user, (that is a good ability, if and if i can customize exception message)

**Comment by fabpot** [comment]
Closing as exception messages are not meant to be displayed to the user.

**Pull request closed without merging**
