### PR TITLE
Added regex for uuid 4

### PR DESCRIPTION
**Pull request by Nyholm**
I use an uuid (v4) in my URL to identify an entity (like you always should). This is a recommended security measure if you compare with just using an auto incremental numeric id (which is standard for a Doctrine/Mysql setup). I want of course make sure that my routes are properly defined and that I have a `requirement` on all my variables. So I write something like this:

```php
/**
* @Route("/show/{uuid}", name="show_user", requirements={"uuid" = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"})
*/
public function showAction(User $user)
```

The regex for the uuid is quite long and horrible to write/remember. This PR allows you to write a shortcut for that ugly regex. So instead you would write: 

```php
/**
 * @Route("/show/{uuid}", name="show_user", requirements={"uuid" = "\uuid4"})
 */
public function showAction(User $user)
```

### CODE REVIEW

**Comment by fabpot** [comment]
That's nice. I thought about adding such shortcuts a few years ago, but never did it. What about adding this support in the Symfony Routing component instead? We could then add more than just UUID.

**Comment by Nyholm** [comment]
Thank you. I would be happy to make a PR to the routing component. I was not sure if you would accept it there. I'll try to create that PR today.

**Comment by Nyholm** [comment]
The core team did not accept my change. It was too much of a hack. 

However, @lyrixx [provided a neat alternative solution](https://github.com/symfony/symfony/pull/18599#issuecomment-212394889). Do we want to merge this PR or should I update the documentation with the alternative solution?

**Comment by xabbuh** [comment]
@Nyholm FYI, @javiereguiluz started a PR on the docs repo: symfony/symfony-docs#6505

**Comment by iltar** [comment]
If this is added to the Route annotation, it will become quite unclear what the differences are between the symfony route and this extension. As it is, I actually rather see this service removed and make a Controller annotation instead due to this confusion.

**Comment by fabpot** [comment]
I think support for this does not belong to this bundle but to Symfony core. As it has been rejected there, I'm closing this PR.

**Pull request closed without merging**
